# 头部菜单，title: link
menu:
  Gold: /Gold
  Github: https://github.com/goldhan

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: true

# 默认音乐
mp3: 
  - https://github.com/goldhan/GDResource/raw/master/Music/%E5%AD%9D%E6%B7%91%20-%20%E6%BE%A4%E9%87%8E%E5%BC%98%E4%B9%8B%20-%20Call%C2%A0of%C2%A0Silence%C2%A0(%E5%AD%9D%E6%B7%91%C2%A0Bootleg).mp3
  - https://github.com/goldhan/GDResource/raw/master/Music/Gareth%20Coker%20-%20Main%20Theme%20-%20Definitive%20Edition.mp3
  - https://github.com/goldhan/GDResource/raw/master/Music/Gareth%20Coker%2CAeralie%20Brighton%20-%20Ori%2C%20Lost%20In%20the%20Storm.mp3
  - https://github.com/goldhan/GDResource/raw/master/Music/Ivan%20Torrent%20-%20Before%20I%20Leave%20This%20World.mp3
  - https://github.com/goldhan/GDResource/raw/master/Music/Kyle%C2%A0Xian%20-%20%E4%B8%80%E5%8F%A3%E6%B0%94%E5%90%AC%E5%AE%8C12%E9%A6%96%E3%80%8A%E8%BE%B6%E4%BA%95%E5%87%BB%E7%9A%84%E5%B7%A8%E4%BA%BA%E3%80%8B%E7%A5%9E%E6%9B%B2%EF%BC%88%E7%B4%85%E8%93%AEX%E5%BF%83%E8%84%8FX%E7%AC%BC%E4%B8%AD%E9%B8%9FX%E5%8F%98%E8%BA%AB%E7%A5%9E%E6%9B%B2xReluctant%20X%20eye%EF%BC%89%EF%BC%88Cover%20Linked%20Horizon%EF%BC%89.mp3
  - https://github.com/goldhan/GDResource/raw/master/Music/Rous%20-%20L.I.F.E.mp3
  - https://github.com/goldhan/GDResource/raw/master/Music/%E4%B8%AD%E6%9D%91%E7%94%B1%E5%88%A9%E5%AD%90%20-%20%E7%81%AB%E5%AE%B5%E3%81%AE%E6%9C%88%E3%83%BB%E3%83%86%E3%83%BC%E3%83%9E~%E3%83%94%E3%82%A2%E3%83%8E%E3%82%BD%E3%83%AD.mp3
  - https://github.com/goldhan/GDResource/raw/master/Music/%E8%8B%B1%E9%9B%84%E8%81%94%E7%9B%9F%20-%20Elementalist%20Lux.mp3
  - https://github.com/goldhan/GDResource/raw/master/Music/%E8%8B%B1%E9%9B%84%E8%81%94%E7%9B%9F%20-%20Freljord.mp3
  - https://github.com/goldhan/GDResource/raw/master/Music/%E8%8B%B1%E9%9B%84%E8%81%94%E7%9B%9F%20-%20Jhin%2C%20the%20Virtuoso.mp3
  - https://github.com/goldhan/GDResource/raw/master/Music/%E8%8B%B1%E9%9B%84%E8%81%94%E7%9B%9F%20-%20Taliyah%2Cthe%20Stoneweaver.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: # /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: '322c43929b0a911a80d0'
    # 应用秘钥
    clientSecret: '7377427a8bdd9d114f65e1e4ddbdcd2c8e5b2192'
    # issue仓库名
    repo: 'goldhan.github.io'
    # Github名
    owner: 'goldhan'
    # Github名
    admin: ['goldhan']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: ['iOS','Gold']

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
